import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const categories = [
  { name: 'TRENDING_SERVICES', displayName: 'TRENDING SERVICES', order: 1 },
  { name: 'VERIFICATION_LISTING', displayName: 'VERIFICATION & LISTING', order: 2 },
  { name: 'UPDATES_INTEGRATION', displayName: 'UPDATES & INTEGRATION', order: 3 },
  { name: 'UPVOTES_ENGAGEMENT', displayName: 'UPVOTES & ENGAGEMENT', order: 4 },
  { name: 'COMMUNITY_BUILDING', displayName: 'COMMUNITY BUILDING', order: 5 },
  { name: 'BANNER_ADVERTISING', displayName: 'BANNER & ADVERTISING', order: 6 },
  { name: 'PRESS_MEDIA', displayName: 'PRESS & MEDIA', order: 7 },
  { name: 'CEX_LISTING', displayName: 'CEX LISTING', order: 8 },
];

const services = [
  // TRENDING SERVICES
  {
    category: 'TRENDING_SERVICES',
    number: 1,
    serviceName: 'Coingecko trending region',
    price: '600',
    requirement: '',
    processingTime: '2-6 Hours',
    duration: '7 days',
    positionBracket: '1-3',
    marketPrice: '750-1000',
    notes: 'Trending on 7 countries | book earlier 1-2 week | US,UK,Brazil,India,Turkey,Philipines,Indonesia',
  },
  {
    category: 'TRENDING_SERVICES',
    number: 2,
    serviceName: 'Coingecko trending region',
    price: '500',
    requirement: '',
    processingTime: '2-6 Hours',
    duration: '7 days',
    positionBracket: '4-7',
    marketPrice: '600-750',
    notes: 'Trending on 7 countries | book earlier 1-2 week | US,UK,Brazil,India,Turkey,Philipines,Indonesia',
  },
  {
    category: 'TRENDING_SERVICES',
    number: 3,
    serviceName: 'Coingecko main trending and search bar',
    price: '150',
    requirement: 'Rank 1-999',
    processingTime: '2-4 hours',
    duration: '24 hours',
    positionBracket: '1-7',
    marketPrice: '200-300',
    notes: 'Global | book earlier 1-2 week',
  },
  {
    category: 'TRENDING_SERVICES',
    number: 4,
    serviceName: 'Coinmarketcap most visited/viewed',
    price: '1500',
    requirement: '2.5 m volume',
    processingTime: '4 hours',
    duration: '7 days',
    positionBracket: '1-3',
    marketPrice: '1750-2000',
    notes: 'Global | book earlier',
  },
  {
    category: 'TRENDING_SERVICES',
    number: 5,
    serviceName: 'Coinmarketcap most visited/viewed',
    price: '1000',
    requirement: '2.5 m volume',
    processingTime: '4 hours',
    duration: '7 days',
    positionBracket: '4-7',
    marketPrice: '1250-1500',
    notes: 'Global | book earlier',
  },
  {
    category: 'TRENDING_SERVICES',
    number: 6,
    serviceName: 'coinmarketcap trending and search bar',
    price: '13000',
    requirement: '3m volume',
    processingTime: '12 hours',
    duration: '24 hours',
    positionBracket: '1-4',
    marketPrice: '15000-17000',
    notes: 'Global | book earlier',
  },
  {
    category: 'TRENDING_SERVICES',
    number: 7,
    serviceName: 'coinmarketcap trending and search bar',
    price: '6000',
    requirement: '1m volume',
    processingTime: '12 Hours',
    duration: '24 hours',
    positionBracket: '5-10',
    marketPrice: '7000-8000',
    notes: 'Global | book earlier',
  },
  {
    category: 'TRENDING_SERVICES',
    number: 8,
    serviceName: 'dextools trending',
    price: '300',
    requirement: '10k vol',
    processingTime: '2-6 Hours',
    duration: '24 hours',
    positionBracket: '1-7',
    marketPrice: '450-600',
    notes: 'Global',
  },
  {
    category: 'TRENDING_SERVICES',
    number: 9,
    serviceName: 'dexscreener trending',
    price: '100',
    requirement: '10k vol',
    processingTime: '1-3 Hours',
    duration: '6 hours',
    positionBracket: '1-7',
    marketPrice: '150-200',
    notes: 'Global',
  },
  {
    category: 'TRENDING_SERVICES',
    number: 10,
    serviceName: 'solscan trending',
    price: '200',
    requirement: '10k vol',
    processingTime: '1-3 Hours',
    duration: '6 hours',
    positionBracket: '8-15',
    marketPrice: '300-400',
    notes: 'Global',
  },
  {
    category: 'TRENDING_SERVICES',
    number: 11,
    serviceName: 'twitter trending #',
    price: '500',
    requirement: '10k vol',
    processingTime: '6-12 hours',
    duration: '6 Hours',
    positionBracket: '1-4',
    marketPrice: '600-800',
    notes: 'Global',
  },
  {
    category: 'TRENDING_SERVICES',
    number: 12,
    serviceName: 'twitter trending $',
    price: '600',
    requirement: '10k vol',
    processingTime: '6-12 hours',
    duration: '6 Hours',
    positionBracket: '1-4',
    marketPrice: '700-900',
    notes: 'Global',
  },
  {
    category: 'TRENDING_SERVICES',
    number: 13,
    serviceName: 'birdeye most visited',
    price: '250',
    requirement: '10k vol',
    processingTime: '6-12 Hours',
    duration: '24 hours',
    positionBracket: '1-7',
    marketPrice: '300-400',
    notes: 'Global',
  },
  {
    category: 'TRENDING_SERVICES',
    number: 14,
    serviceName: 'birdeye most watched',
    price: '250',
    requirement: '10k vol',
    processingTime: '6-12 Hours',
    duration: '24 hours',
    positionBracket: '1-7',
    marketPrice: '300-400',
    notes: 'Global',
  },
  {
    category: 'TRENDING_SERVICES',
    number: 15,
    serviceName: 'reddit cms trending',
    price: '150',
    requirement: '10k vol',
    processingTime: '6-12 Hours',
    duration: '24 hours',
    positionBracket: '1-7',
    marketPrice: '200-300',
    notes: 'Global',
  },
  {
    category: 'TRENDING_SERVICES',
    number: 16,
    serviceName: 'sub reddit  trending',
    price: '150',
    requirement: '10k vol',
    processingTime: '6-12 Hours',
    duration: '24 hours',
    positionBracket: '1-7',
    marketPrice: '200-300',
    notes: 'Global',
  },
  {
    category: 'TRENDING_SERVICES',
    number: 17,
    serviceName: 'dexview trending',
    price: '200',
    requirement: '10k vol',
    processingTime: '6-12 Hours',
    duration: '24 hours',
    positionBracket: '1-7',
    marketPrice: '250-350',
    notes: 'Global',
  },
  {
    category: 'TRENDING_SERVICES',
    number: 18,
    serviceName: 'coincodex trending',
    price: '150',
    requirement: '10k vol',
    processingTime: '6-12 Hours',
    duration: '24 hours',
    positionBracket: '1-7',
    marketPrice: '200-300',
    notes: 'Global',
  },
  {
    category: 'TRENDING_SERVICES',
    number: 19,
    serviceName: 'dropstab trending',
    price: '100',
    requirement: '10k vol',
    processingTime: '6-12 Hours',
    duration: '24 hours',
    positionBracket: '1-7',
    marketPrice: '150-250',
    notes: 'Global',
  },
  {
    category: 'TRENDING_SERVICES',
    number: 20,
    serviceName: 'token insight trending',
    price: '200',
    requirement: '10k vol',
    processingTime: '6-12 Hours',
    duration: '24 hours',
    positionBracket: '1-7',
    marketPrice: '250-350',
    notes: 'Global',
  },
  {
    category: 'TRENDING_SERVICES',
    number: 21,
    serviceName: 'crypto com trending',
    price: '300',
    requirement: '10k vol',
    processingTime: '12-24 Hours',
    duration: '24 hours',
    positionBracket: '1-7',
    marketPrice: '400-500',
    notes: 'Global',
  },
  {
    category: 'TRENDING_SERVICES',
    number: 22,
    serviceName: 'crypto com most popular',
    price: '300',
    requirement: '10k vol',
    processingTime: '12-24 Hours',
    duration: '24 hours',
    positionBracket: '1-7',
    marketPrice: '400-500',
    notes: 'Global',
  },
  {
    category: 'TRENDING_SERVICES',
    number: 23,
    serviceName: 'coincheckup pupular',
    price: '150',
    requirement: '10k vol',
    processingTime: '6-12 Hours',
    duration: '24 hours',
    positionBracket: '1-7',
    marketPrice: '200-300',
    notes: 'Global',
  },
  {
    category: 'TRENDING_SERVICES',
    number: 24,
    serviceName: 'geckoterminal trending',
    price: '200',
    requirement: '10k vol',
    processingTime: '6-12 Hours',
    duration: '24 hours',
    positionBracket: '1-7',
    marketPrice: '250-350',
    notes: 'Global',
  },

  // VERIFICATION & LISTING
  {
    category: 'VERIFICATION_LISTING',
    number: 1,
    serviceName: 'Coingecko listing',
    price: '250',
    requirement: '100k volume,20-40k lp',
    processingTime: '24-96 Hours',
    duration: '',
    positionBracket: '',
    marketPrice: '500-1000',
    notes: 'Global',
  },
  {
    category: 'VERIFICATION_LISTING',
    number: 2,
    serviceName: 'coinmarketcap listing',
    price: '5500',
    requirement: '',
    processingTime: '24-72 hours',
    duration: '',
    positionBracket: '',
    marketPrice: '6-7.5K',
    notes: 'Global',
  },
  {
    category: 'VERIFICATION_LISTING',
    number: 3,
    serviceName: 'livecoinwatch listing',
    price: '300',
    requirement: '100k volume',
    processingTime: '24-96 Hours',
    duration: '',
    positionBracket: '',
    marketPrice: '400-600',
    notes: 'Global',
  },
  {
    category: 'VERIFICATION_LISTING',
    number: 4,
    serviceName: 'certik audit',
    price: 'Custom',
    requirement: 'Smart contract',
    processingTime: '1-2 weeks',
    duration: '',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Contact for details',
  },
  {
    category: 'VERIFICATION_LISTING',
    number: 5,
    serviceName: 'certik kyc',
    price: 'Custom',
    requirement: 'Team info',
    processingTime: '3-7 days',
    duration: '',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Contact for details',
  },
  {
    category: 'VERIFICATION_LISTING',
    number: 6,
    serviceName: 'listing on voting sites',
    price: '100',
    requirement: 'Basic info',
    processingTime: '24-48 Hours',
    duration: '',
    positionBracket: '',
    marketPrice: '150-250',
    notes: 'Multiple sites',
  },
  {
    category: 'VERIFICATION_LISTING',
    number: 7,
    serviceName: 'coinmarketcap supply verification',
    price: '200',
    requirement: 'Listed on CMC',
    processingTime: '48-96 Hours',
    duration: '',
    positionBracket: '',
    marketPrice: '300-500',
    notes: 'Blue tick verification',
  },
  {
    category: 'VERIFICATION_LISTING',
    number: 8,
    serviceName: 'coingecko suplly verification',
    price: '200',
    requirement: 'Listed on CG',
    processingTime: '48-96 Hours',
    duration: '',
    positionBracket: '',
    marketPrice: '300-500',
    notes: 'Blue tick verification',
  },
  {
    category: 'VERIFICATION_LISTING',
    number: 9,
    serviceName: 'coinmarketcap adding categories',
    price: '100',
    requirement: 'Listed on CMC',
    processingTime: '24-48 Hours',
    duration: '',
    positionBracket: '',
    marketPrice: '150-250',
    notes: 'Up to 3 categories',
  },
  {
    category: 'VERIFICATION_LISTING',
    number: 10,
    serviceName: 'coingecko adding categories',
    price: '100',
    requirement: 'Listed on CG',
    processingTime: '24-48 Hours',
    duration: '',
    positionBracket: '',
    marketPrice: '150-250',
    notes: 'Up to 3 categories',
  },
  {
    category: 'VERIFICATION_LISTING',
    number: 11,
    serviceName: 'coinmarketcap contract migration',
    price: '300',
    requirement: 'Listed on CMC',
    processingTime: '48-96 Hours',
    duration: '',
    positionBracket: '',
    marketPrice: '400-600',
    notes: 'Contract address change',
  },
  {
    category: 'VERIFICATION_LISTING',
    number: 12,
    serviceName: 'coingecko contract migration',
    price: '300',
    requirement: 'Listed on CG',
    processingTime: '48-96 Hours',
    duration: '',
    positionBracket: '',
    marketPrice: '400-600',
    notes: 'Contract address change',
  },
  {
    category: 'VERIFICATION_LISTING',
    number: 13,
    serviceName: 'coinmarketcap red flag removal',
    price: '500',
    requirement: 'Listed on CMC',
    processingTime: '48-120 Hours',
    duration: '',
    positionBracket: '',
    marketPrice: '700-1000',
    notes: 'Case by case basis',
  },
  {
    category: 'VERIFICATION_LISTING',
    number: 14,
    serviceName: 'coingecko red flag removal',
    price: '500',
    requirement: 'Listed on CG',
    processingTime: '48-120 Hours',
    duration: '',
    positionBracket: '',
    marketPrice: '700-1000',
    notes: 'Case by case basis',
  },
  {
    category: 'VERIFICATION_LISTING',
    number: 15,
    serviceName: 'coinmarketcap adding market',
    price: '150',
    requirement: 'Listed on CMC',
    processingTime: '24-72 Hours',
    duration: '',
    positionBracket: '',
    marketPrice: '200-350',
    notes: 'Add new trading pair',
  },
  {
    category: 'VERIFICATION_LISTING',
    number: 16,
    serviceName: 'coingecko adding market',
    price: '150',
    requirement: 'Listed on CG',
    processingTime: '24-72 Hours',
    duration: '',
    positionBracket: '',
    marketPrice: '200-350',
    notes: 'Add new trading pair',
  },

  // UPDATES & INTEGRATION
  {
    category: 'UPDATES_INTEGRATION',
    number: 1,
    serviceName: 'dextools update',
    price: '750-850',
    requirement: '',
    processingTime: '1-2 Hours',
    duration: '',
    positionBracket: '',
    marketPrice: '3 bnb/0.4 ETH/5 SOL',
    notes: 'Global',
  },
  {
    category: 'UPDATES_INTEGRATION',
    number: 2,
    serviceName: 'ave update',
    price: '300',
    requirement: '',
    processingTime: '1-2 Hours',
    duration: '',
    positionBracket: '',
    marketPrice: '350-500',
    notes: 'Global',
  },
  {
    category: 'UPDATES_INTEGRATION',
    number: 3,
    serviceName: 'dexscrener update',
    price: '299',
    requirement: '',
    processingTime: '1-2 Hours',
    duration: '',
    positionBracket: '',
    marketPrice: '300-400',
    notes: 'Global',
  },
  {
    category: 'UPDATES_INTEGRATION',
    number: 4,
    serviceName: 'birdeye update',
    price: '350',
    requirement: '',
    processingTime: '24 hours',
    duration: '',
    positionBracket: '',
    marketPrice: '350-500',
    notes: 'Global',
  },
  {
    category: 'UPDATES_INTEGRATION',
    number: 5,
    serviceName: 'trust wallet swap+logo',
    price: '200',
    requirement: 'Listed token',
    processingTime: '48-72 Hours',
    duration: '',
    positionBracket: '',
    marketPrice: '300-450',
    notes: 'Mobile wallet integration',
  },

  // UPVOTES & ENGAGEMENT
  {
    category: 'UPVOTES_ENGAGEMENT',
    number: 1,
    serviceName: 'dextools votes',
    price: '50',
    requirement: '',
    processingTime: '1-6 Hours',
    duration: '',
    positionBracket: '100 votes',
    marketPrice: '70-100',
    notes: 'Organic looking votes',
  },
  {
    category: 'UPVOTES_ENGAGEMENT',
    number: 2,
    serviceName: 'coinmarketcap wachlist',
    price: '100',
    requirement: '',
    processingTime: '12-24 Hours',
    duration: '',
    positionBracket: '1000 adds',
    marketPrice: '150-250',
    notes: 'Increase watchlist count',
  },
  {
    category: 'UPVOTES_ENGAGEMENT',
    number: 3,
    serviceName: 'coingecko watchlist \\stars',
    price: '100',
    requirement: '',
    processingTime: '12-24 Hours',
    duration: '',
    positionBracket: '1000 adds',
    marketPrice: '150-250',
    notes: 'Increase watchlist count',
  },
  {
    category: 'UPVOTES_ENGAGEMENT',
    number: 4,
    serviceName: 'coinmarketcap followers',
    price: '100',
    requirement: 'CMC profile',
    processingTime: '24-48 Hours',
    duration: '',
    positionBracket: '1000 followers',
    marketPrice: '150-250',
    notes: 'Profile engagement',
  },
  {
    category: 'UPVOTES_ENGAGEMENT',
    number: 5,
    serviceName: 'coinmarketcap likes',
    price: '150',
    requirement: 'CMC profile',
    processingTime: '12-24 Hours',
    duration: '',
    positionBracket: '1000 likes',
    marketPrice: '200-350',
    notes: 'Post interaction boost',
  },
  {
    category: 'UPVOTES_ENGAGEMENT',
    number: 6,
    serviceName: 'coinmarketcap dexscan thumbs',
    price: '50',
    requirement: '',
    processingTime: '6-12 Hours',
    duration: '',
    positionBracket: '100 thumbs',
    marketPrice: '70-100',
    notes: 'Dexscan engagement',
  },
  {
    category: 'UPVOTES_ENGAGEMENT',
    number: 7,
    serviceName: 'upvoting on voting sites',
    price: '100',
    requirement: '',
    processingTime: '24-48 Hours',
    duration: '',
    positionBracket: 'Multiple sites',
    marketPrice: '150-250',
    notes: 'Coinsniper, Coinhunt, etc',
  },
  {
    category: 'UPVOTES_ENGAGEMENT',
    number: 8,
    serviceName: 'dexscreener rocket and fire',
    price: '50',
    requirement: '',
    processingTime: '1-6 Hours',
    duration: '',
    positionBracket: '100 rockets',
    marketPrice: '70-100',
    notes: 'Organic engagement',
  },
  {
    category: 'UPVOTES_ENGAGEMENT',
    number: 9,
    serviceName: 'coinmarketcap bullish comments',
    price: '150',
    requirement: 'Listed on CMC',
    processingTime: '24-48 Hours',
    duration: '',
    positionBracket: '50 comments',
    marketPrice: '200-300',
    notes: 'Positive sentiment comments',
  },
  {
    category: 'UPVOTES_ENGAGEMENT',
    number: 10,
    serviceName: 'twitter folowers',
    price: '100',
    requirement: '',
    processingTime: '24-48 Hours',
    duration: '',
    positionBracket: '1000 followers',
    marketPrice: '150-250',
    notes: 'Real looking accounts',
  },
  {
    category: 'UPVOTES_ENGAGEMENT',
    number: 11,
    serviceName: 'twitter likes',
    price: '30',
    requirement: '',
    processingTime: '6-12 Hours',
    duration: '',
    positionBracket: '1000 likes',
    marketPrice: '50-80',
    notes: 'Organic engagement',
  },
  {
    category: 'UPVOTES_ENGAGEMENT',
    number: 12,
    serviceName: 'twitters possitive comments',
    price: '100',
    requirement: '',
    processingTime: '12-24 Hours',
    duration: '',
    positionBracket: '100 comments',
    marketPrice: '150-250',
    notes: 'Targeted positive comments',
  },

  // COMMUNITY BUILDING
  {
    category: 'COMMUNITY_BUILDING',
    number: 1,
    serviceName: 'discord member',
    price: '100',
    requirement: '',
    processingTime: '24-48 Hours',
    duration: '',
    positionBracket: '1000 members',
    marketPrice: '150-250',
    notes: 'Real looking accounts',
  },
  {
    category: 'COMMUNITY_BUILDING',
    number: 2,
    serviceName: 'telegram member',
    price: '100',
    requirement: '',
    processingTime: '24-48 Hours',
    duration: '',
    positionBracket: '1000 members',
    marketPrice: '150-250',
    notes: 'Real looking accounts',
  },
  {
    category: 'COMMUNITY_BUILDING',
    number: 3,
    serviceName: 'telegram online member',
    price: '50',
    requirement: 'Existing group',
    processingTime: 'Instant',
    duration: '24 Hours',
    positionBracket: '100 online',
    marketPrice: '80-120',
    notes: 'Boost online count',
  },
  {
    category: 'COMMUNITY_BUILDING',
    number: 4,
    serviceName: 'telegram mass DM',
    price: '200',
    requirement: 'Group access',
    processingTime: '24-48 Hours',
    duration: '',
    positionBracket: '1000 DMs',
    marketPrice: '300-400',
    notes: 'Targeted messaging',
  },
  {
    category: 'COMMUNITY_BUILDING',
    number: 5,
    serviceName: 'telegram scraping members',
    price: '150',
    requirement: 'Target groups',
    processingTime: '24-48 Hours',
    duration: '',
    positionBracket: 'Extract members',
    marketPrice: '200-300',
    notes: 'Member list extraction',
  },
  {
    category: 'COMMUNITY_BUILDING',
    number: 6,
    serviceName: 'telegram shilling',
    price: '100',
    requirement: '',
    processingTime: '24-48 Hours',
    duration: '',
    positionBracket: 'Targeted groups',
    marketPrice: '150-250',
    notes: 'Group promotion',
  },
  {
    category: 'COMMUNITY_BUILDING',
    number: 7,
    serviceName: 'telegram moderator',
    price: 'Custom',
    requirement: 'Ongoing',
    processingTime: 'Monthly',
    duration: '',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Community management',
  },
  {
    category: 'COMMUNITY_BUILDING',
    number: 8,
    serviceName: 'twitter retweet',
    price: '50',
    requirement: '',
    processingTime: '6-12 Hours',
    duration: '',
    positionBracket: '500 retweets',
    marketPrice: '80-120',
    notes: 'Organic engagement',
  },
  {
    category: 'COMMUNITY_BUILDING',
    number: 9,
    serviceName: 'twitter quote retweet',
    price: '75',
    requirement: '',
    processingTime: '6-12 Hours',
    duration: '',
    positionBracket: '250 quote RTs',
    marketPrice: '100-150',
    notes: 'Organic engagement',
  },
  {
    category: 'COMMUNITY_BUILDING',
    number: 10,
    serviceName: 'twitter post',
    price: 'Custom',
    requirement: 'Content provided',
    processingTime: '24-48 Hours',
    duration: '',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Professional content creation',
  },

  // BANNER & ADVERTISING
  {
    category: 'BANNER_ADVERTISING',
    number: 1,
    serviceName: 'dexview banner ads',
    price: '175',
    requirement: '',
    processingTime: '2-6 hours',
    duration: '1 day',
    positionBracket: '',
    marketPrice: '200-250',
    notes: 'Global',
  },
  {
    category: 'BANNER_ADVERTISING',
    number: 2,
    serviceName: 'dexscreener banner ads',
    price: '175',
    requirement: '',
    processingTime: '2-6 hours',
    duration: '1 day',
    positionBracket: '',
    marketPrice: '200-250',
    notes: 'Global',
  },
  {
    category: 'BANNER_ADVERTISING',
    number: 3,
    serviceName: 'dexview banner ads',
    price: '175',
    requirement: '',
    processingTime: '2-6 hours',
    duration: '1 week',
    positionBracket: '',
    marketPrice: '200-250',
    notes: 'Global',
  },
  {
    category: 'BANNER_ADVERTISING',
    number: 4,
    serviceName: '4chan banners',
    price: '300',
    requirement: '',
    processingTime: '24-48 Hours',
    duration: '1 week',
    positionBracket: '',
    marketPrice: '400-600',
    notes: '/biz/ board',
  },
  {
    category: 'BANNER_ADVERTISING',
    number: 5,
    serviceName: 'bilboard  las vegas',
    price: 'Custom',
    requirement: 'High visibility',
    processingTime: 'Negotiable',
    duration: 'Varies',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Physical billboard',
  },
  {
    category: 'BANNER_ADVERTISING',
    number: 6,
    serviceName: 'bilboard spaceX',
    price: 'Custom',
    requirement: 'High visibility',
    processingTime: 'Negotiable',
    duration: 'Varies',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Physical billboard',
  },
  {
    category: 'BANNER_ADVERTISING',
    number: 7,
    serviceName: 'bilboard hongkong',
    price: 'Custom',
    requirement: 'High visibility',
    processingTime: 'Negotiable',
    duration: 'Varies',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Physical billboard',
  },
  {
    category: 'BANNER_ADVERTISING',
    number: 8,
    serviceName: 'bilboard new york',
    price: 'Custom',
    requirement: 'High visibility',
    processingTime: 'Negotiable',
    duration: 'Varies',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Physical billboard',
  },
  {
    category: 'BANNER_ADVERTISING',
    number: 9,
    serviceName: 'poocoin banner',
    price: '300',
    requirement: '',
    processingTime: '24-48 Hours',
    duration: '7 days',
    positionBracket: '',
    marketPrice: '400-600',
    notes: 'BSC focused traffic',
  },
  {
    category: 'BANNER_ADVERTISING',
    number: 10,
    serviceName: 'coinmooner banner ads',
    price: '250',
    requirement: '',
    processingTime: '24-48 Hours',
    duration: '7 days',
    positionBracket: '',
    marketPrice: '350-500',
    notes: 'Crypto traffic',
  },
  {
    category: 'BANNER_ADVERTISING',
    number: 11,
    serviceName: 'coindiscovery banner ads',
    price: '250',
    requirement: '',
    processingTime: '24-48 Hours',
    duration: '7 days',
    positionBracket: '',
    marketPrice: '350-500',
    notes: 'Crypto traffic',
  },
  {
    category: 'BANNER_ADVERTISING',
    number: 12,
    serviceName: 'coingecko banner ads',
    price: 'Custom',
    requirement: 'High traffic',
    processingTime: 'Negotiable',
    duration: 'Varies',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Contact for rates',
  },
  {
    category: 'BANNER_ADVERTISING',
    number: 13,
    serviceName: 'dextools banner ads',
    price: 'Custom',
    requirement: 'High traffic',
    processingTime: 'Negotiable',
    duration: 'Varies',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Contact for rates',
  },
  {
    category: 'BANNER_ADVERTISING',
    number: 14,
    serviceName: 'etherscan banner ads',
    price: 'Custom',
    requirement: 'High traffic',
    processingTime: 'Negotiable',
    duration: 'Varies',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Contact for rates',
  },
  {
    category: 'BANNER_ADVERTISING',
    number: 15,
    serviceName: 'etherscan text banner',
    price: 'Custom',
    requirement: 'High traffic',
    processingTime: 'Negotiable',
    duration: 'Varies',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Contact for rates',
  },
  {
    category: 'BANNER_ADVERTISING',
    number: 16,
    serviceName: 'bsc banner ads',
    price: 'Custom',
    requirement: 'High traffic',
    processingTime: 'Negotiable',
    duration: 'Varies',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Contact for rates',
  },
  {
    category: 'BANNER_ADVERTISING',
    number: 17,
    serviceName: 'bscscan banner ads',
    price: 'Custom',
    requirement: 'High traffic',
    processingTime: 'Negotiable',
    duration: 'Varies',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Contact for rates',
  },

  // PRESS & MEDIA
  {
    category: 'PRESS_MEDIA',
    number: 1,
    serviceName: 'coinmarketcap article feed',
    price: '300',
    requirement: '',
    processingTime: '24-48 Hours',
    duration: 'Permanent',
    positionBracket: '',
    marketPrice: '500-700',
    notes: 'CMC news feed',
  },
  {
    category: 'PRESS_MEDIA',
    number: 2,
    serviceName: 'binance article feed',
    price: '400',
    requirement: '',
    processingTime: '24-48 Hours',
    duration: 'Permanent',
    positionBracket: '',
    marketPrice: '600-800',
    notes: 'Binance news feed',
  },
  {
    category: 'PRESS_MEDIA',
    number: 3,
    serviceName: 'gate article feed',
    price: '300',
    requirement: '',
    processingTime: '24-48 Hours',
    duration: 'Permanent',
    positionBracket: '',
    marketPrice: '500-700',
    notes: 'Gate.io news feed',
  },
  {
    category: 'PRESS_MEDIA',
    number: 4,
    serviceName: 'medium article feed',
    price: '200',
    requirement: '',
    processingTime: '24-48 Hours',
    duration: 'Permanent',
    positionBracket: '',
    marketPrice: '300-450',
    notes: 'Medium publication',
  },
  {
    category: 'PRESS_MEDIA',
    number: 5,
    serviceName: 'bitcointalk article feed',
    price: '250',
    requirement: '',
    processingTime: '24-48 Hours',
    duration: 'Permanent',
    positionBracket: '',
    marketPrice: '400-600',
    notes: 'Bitcointalk announcement',
  },

  // CEX LISTING
  {
    category: 'CEX_LISTING',
    number: 1,
    serviceName: 'HUOBI',
    price: 'Custom',
    requirement: 'Strong volume & community',
    processingTime: '2-4 weeks',
    duration: '',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Tier 2 - Contact for details',
  },
  {
    category: 'CEX_LISTING',
    number: 2,
    serviceName: 'KUCOIN',
    price: 'Custom',
    requirement: 'Strong volume & community',
    processingTime: '2-4 weeks',
    duration: '',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Tier 1 - Contact for details',
  },
  {
    category: 'CEX_LISTING',
    number: 3,
    serviceName: 'GATE',
    price: 'Custom',
    requirement: 'Strong volume & community',
    processingTime: '2-4 weeks',
    duration: '',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Tier 2 - Contact for details',
  },
  {
    category: 'CEX_LISTING',
    number: 4,
    serviceName: 'BITGET',
    price: 'Custom',
    requirement: 'Strong volume & community',
    processingTime: '2-4 weeks',
    duration: '',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Tier 1 - Contact for details',
  },
  {
    category: 'CEX_LISTING',
    number: 5,
    serviceName: 'BING X',
    price: 'Custom',
    requirement: 'Strong volume & community',
    processingTime: '2-4 weeks',
    duration: '',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Tier 2 - Contact for details',
  },
  {
    category: 'CEX_LISTING',
    number: 6,
    serviceName: 'POLONIEX',
    price: 'Custom',
    requirement: 'Strong volume & community',
    processingTime: '1-2 weeks',
    duration: '',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Tier 3 - Contact for details',
  },
  {
    category: 'CEX_LISTING',
    number: 7,
    serviceName: 'MEXC',
    price: 'Custom',
    requirement: 'Strong volume & community',
    processingTime: '2-4 weeks',
    duration: '',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Tier 2 - Contact for details',
  },
  {
    category: 'CEX_LISTING',
    number: 8,
    serviceName: 'LBANK',
    price: 'Custom',
    requirement: 'Strong volume & community',
    processingTime: '2-4 weeks',
    duration: '',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Tier 2 - Contact for details',
  },
  {
    category: 'CEX_LISTING',
    number: 9,
    serviceName: 'BITMART',
    price: 'Custom',
    requirement: 'Strong volume & community',
    processingTime: '2-4 weeks',
    duration: '',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Tier 2 - Contact for details',
  },
  {
    category: 'CEX_LISTING',
    number: 10,
    serviceName: 'HOTCOIN',
    price: 'Custom',
    requirement: 'Strong volume & community',
    processingTime: '1-2 weeks',
    duration: '',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Tier 3 - Contact for details',
  },
  {
    category: 'CEX_LISTING',
    number: 11,
    serviceName: 'XT',
    price: 'Custom',
    requirement: 'Strong volume & community',
    processingTime: '1-2 weeks',
    duration: '',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Tier 3 - Contact for details',
  },
  {
    category: 'CEX_LISTING',
    number: 12,
    serviceName: 'BIGONE',
    price: 'Custom',
    requirement: 'Strong volume & community',
    processingTime: '1-2 weeks',
    duration: '',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Tier 3 - Contact for details',
  },
  {
    category: 'CEX_LISTING',
    number: 13,
    serviceName: 'ASCENDEX',
    price: 'Custom',
    requirement: 'Strong volume & community',
    processingTime: '1-2 weeks',
    duration: '',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Tier 3 - Contact for details',
  },
  {
    category: 'CEX_LISTING',
    number: 14,
    serviceName: 'COINW',
    price: 'Custom',
    requirement: 'Strong volume & community',
    processingTime: '1-2 weeks',
    duration: '',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Tier 3 - Contact for details',
  },
  {
    category: 'CEX_LISTING',
    number: 15,
    serviceName: 'PROBIT',
    price: 'Custom',
    requirement: 'Strong volume & community',
    processingTime: '1-2 weeks',
    duration: '',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Tier 3 - Contact for details',
  },
  {
    category: 'CEX_LISTING',
    number: 16,
    serviceName: 'BITRUE',
    price: 'Custom',
    requirement: 'Strong volume & community',
    processingTime: '1-2 weeks',
    duration: '',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Tier 3 - Contact for details',
  },
  {
    category: 'CEX_LISTING',
    number: 17,
    serviceName: 'DIGIFINEX',
    price: 'Custom',
    requirement: 'Strong volume & community',
    processingTime: '1-2 weeks',
    duration: '',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Tier 3 - Contact for details',
  },
  {
    category: 'CEX_LISTING',
    number: 18,
    serviceName: 'P2B',
    price: 'Custom',
    requirement: 'Strong volume & community',
    processingTime: '1-2 weeks',
    duration: '',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Tier 3 - Contact for details',
  },
  {
    category: 'CEX_LISTING',
    number: 19,
    serviceName: 'CITEX',
    price: 'Custom',
    requirement: 'Strong volume & community',
    processingTime: '1-2 weeks',
    duration: '',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Tier 3 - Contact for details',
  },
  {
    category: 'CEX_LISTING',
    number: 20,
    serviceName: 'LATOKEN',
    price: 'Custom',
    requirement: 'Strong volume & community',
    processingTime: '1-2 weeks',
    duration: '',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Tier 3 - Contact for details',
  },
  {
    category: 'CEX_LISTING',
    number: 21,
    serviceName: 'COINSTORE',
    price: 'Custom',
    requirement: 'Strong volume & community',
    processingTime: '1-2 weeks',
    duration: '',
    positionBracket: '',
    marketPrice: 'Custom',
    notes: 'Tier 3 - Contact for details',
  },
];

async function main() {
  console.log('Starting seed...');

  // Create categories
  console.log('Creating categories...');
  for (const category of categories) {
    await prisma.category.upsert({
      where: { name: category.name },
      update: {},
      create: category,
    });
  }

  // Create services
  console.log('Creating services...');
  for (const service of services) {
    const category = await prisma.category.findUnique({
      where: { name: service.category },
    });

    if (!category) {
      console.error(`Category ${service.category} not found`);
      continue;
    }

    await prisma.service.upsert({
      where: {
        categoryId_number: {
          categoryId: category.id,
          number: service.number,
        },
      },
      update: {
        serviceName: service.serviceName,
        price: service.price,
        requirement: service.requirement || null,
        processingTime: service.processingTime || null,
        duration: service.duration || null,
        positionBracket: service.positionBracket || null,
        marketPrice: service.marketPrice || null,
        notes: service.notes || null,
      },
      create: {
        categoryId: category.id,
        number: service.number,
        serviceName: service.serviceName,
        price: service.price,
        requirement: service.requirement || null,
        processingTime: service.processingTime || null,
        duration: service.duration || null,
        positionBracket: service.positionBracket || null,
        marketPrice: service.marketPrice || null,
        notes: service.notes || null,
      },
    });
  }

  console.log('Seed completed successfully!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
